steps:
  push-tagged-build:
    image: plugins/docker
    settings:
      repo: lblod/gelinkt-notuleren-consumer
      tags: "${CI_COMMIT_TAG##v}"
      purge: true
    secrets: [ docker_username, docker_password ]
when:
  event: tag
  ref: refs/tags/v*
